version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["air"]
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
