version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: ["air"]
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydb
  db:
    image: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - ./pgdata:/var/lib/postgresql/data